service: botson-2-0
variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  lambdaHashingVersion: 20201221

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:Scan"
          Resource:
            - "arn:aws:dynamodb:*:*:table/guestbookTable"

        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
          Resource:
            - "arn:aws:dynamodb:*:*:table/permissionsTable"

resources:
  Resources:
    guestbookTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.GUESTBOOK_TABLE}
        AttributeDefinitions:
          - AttributeName: messageId
            AttributeType: S
        KeySchema:
          - AttributeName: messageId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    permissionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.PERMISSIONS_TABLE}
        AttributeDefinitions:
          - AttributeName: senderId
            AttributeType: S
        KeySchema:
          - AttributeName: senderId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1 

functions:
  webhook_verify:
    handler: rest_api/webhook/get/handler.handle
    description: Used by Facebook for verifying webhook
    timeout: 10
    events:
      - http:
          path: /webhook
          method: get
    environment:
      VERIFY_TOKEN: ${ssm:/botson-facebook-verification-token}

  webhook_post:
    handler: rest_api/webhook/post/handler.handle
    description: Handle incoming messages and events
    timeout: 10
    events:
      - http:
          path: /webhook
          method: post
    environment:
      PAGE_ACCESS_TOKEN: ${ssm:/botson-facebook-page-access-token}
      GUESTBOOK_TABLE: ${self:custom.GUESTBOOK_TABLE}
      PERMISSIONS_TABLE: ${self:custom.PERMISSIONS_TABLE}
      TYPING_MS: 0

custom:
  GUESTBOOK_TABLE: guestbookTable
  PERMISSIONS_TABLE: permissionsTable
